import { useState, useEffect, FormEvent } from "react";
import { initializeApp } from "firebase/app";
import {
  getAuth,
  sendPasswordResetEmail,
  signInWithEmailAndPassword,
} from "firebase/auth";
import { useNavigate } from "react-router-dom";
import { firebaseConfig } from "../../config/firebaseConfig";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../../css/reset-password.css";
import { useStyle } from "../../context/StyleContext";
import RedKing from "../../assets/img/redKing.png";
import BlackKing from "../../assets/img/blackKing.png";
import { Link } from "react-router-dom";
import backgroundImage from "../../assets/img/background.png";

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

/**
 * Provides a form for users to reset their password. Users can enter their email address to receive
 * a password reset link. It uses Firebase authentication to handle the password reset process.
 * The background and theming are managed using the `useStyle` context.
 */
const ResetPassword = () => {
  // State to hold the email input
  const [email, setEmail] = useState("");
  const navigate = useNavigate();

  const { changeBodyBackground } = useStyle();

  /**
   * Sets the background image on component mount and reverts it back to default on unmount.
   */
  useEffect(() => {
    changeBodyBackground(backgroundImage);
    return () => changeBodyBackground("wheat");
  }, [changeBodyBackground]);

  /**
   * Handles the submission of the reset password form. Validates the email address and requests
   * Firebase Auth service to send a password reset email. Displays a success or error message based
   * on the outcome.
   *
   * @param {FormEvent} e - The event generated by form submission.
   */
  const handleResetPassword = (e: FormEvent) => {
    e.preventDefault();
    if (!email) {
      toast.error("Please enter your email address!");
      return;
    }

    sendPasswordResetEmail(auth, email)
      .then(() => {
        toast.success(
          "Password reset email sent successfully. Please check your inbox."
        );
      })
      .catch((error) => {
        toast.error(`Error sending password reset email: ${error.message}`);
      });
  };

  return (
    <>
      <ToastContainer />
      <div className="main">
        <form
          className="main-reset-container"
          onSubmit={(e) => {
            e.preventDefault();
            handleResetPassword(e);
          }}
        >
          <div className="main-header">
            <h3>Reset Password</h3>
          </div>
          <div className="main-central-img">
            <img src={BlackKing} alt="" className="black" />
            <img src={RedKing} alt="" className="red" />
          </div>
          <div className="main-info-forms">
            <label htmlFor="email">
              <b>Email</b>
            </label>
            <input
              id="email"
              type="email"
              placeholder="Enter Email"
              name="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div className="flex-container">
            <div className="main-central-btn">
              <button type="submit">Reset</button>
            </div>
            <button className="main-login-btn">
              <Link to="/">Login instead</Link>
            </button>
          </div>
        </form>
      </div>
    </>
  );
};

export default ResetPassword;
